matrix:
  include:
    - language: php
      php: 7.1
      before_script:
        - cd app
        - composer self-update
        - composer install
      script: composer lint

    - language: node_js
      node_js:
        - node
        - '9'
      before_script:
        - cd app
        - npm install -g tslint typescript
      script: yarn lint

    - language: php
      php: 7.1
      services:
        - mysql
      before_script:
        - cd app
        - composer self-update
        - composer install
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
        - export PATH="$HOME/.yarn/bin:$PATH"
        - yarn install
        - yarn build
      script: php bin/phpunit --coverage-text

    - language: node_js
      node_js:
        - node
        - '9'
      before_script:
        - cd app
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
        - export PATH="$HOME/.yarn/bin:$PATH"
        - yarn install
      script: yarn test