version: "3"
services:
  web:
    image: qeep/numidium
    ports:
      - "8000:80"
    environment:
      - CORS_ALLOW_ORIGIN=*
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - RUN_SCRIPTS=1
      - APP_SECRET=Secret-Key
