api_me:
    path: /api/me
    methods: [GET]
    controller: App\Controller\MeController::getId

front:
    path: /{req}
    controller: App\Controller\FrontController::index
    requirements:
        req: ".*"