services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\DataFixtures\:
        resource: '../src/DataFixtures/*'
    
    test.App\DataFixtures\UserFixtures:     '@App\DataFixtures\UserFixtures'