services:
    _defaults:
        public: true

    test.App\DataFixtures\UserFixtures:     '@App\DataFixtures\UserFixtures'
    test.App\DataFixtures\VacationFixtures: '@App\DataFixtures\VacationFixtures'