framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    php_errors:
        log: true

    cache:
